[server]
maxUploadSize = 50
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#0a0a0a"
primaryColor = "#38bdf8"
textColor = "#ededed"
